apiVersion: v1
kind: Service
metadata:
  name: eventmanager-service
spec:
  type: NodePort
  ports:
    - port: 80           # Este es el puerto del servicio en el clúster
      targetPort: 8080   # Este es el puerto donde la aplicación escucha
      nodePort: 30714    # Este es el puerto que usas para acceder desde fuera
  selector:
    app: eventmanager
